// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"
export var Destination;
(function (Destination) {
    Destination["Barra"] = "Barra";
})(Destination || (Destination = {}));
